/*---------------------------------------------------------------------------*/

#ifndef uqtopusBoundaryConditionFvPatchFieldsFwd_H
#define uqtopusBoundaryConditionFvPatchFieldsFwd_H

#include "fieldTypes.H"

namespace Foam
{

template<class Type> class uqtopusBoundaryConditionFvPatchField;

makePatchTypeFieldTypedefs(uqtopusBoundaryCondition);

} // End namespace Foam

#endif

// ************************************************************************* //
