/*---------------------------------------------------------------------------*/

#ifndef uqtopusBoundaryConditionFvPatchFields_H
#define uqtopusBoundaryConditionFvPatchFields_H

#include "uqtopusBoundaryConditionFvPatchField.H"
#include "fieldTypes.H"

namespace Foam
{

makePatchTypeFieldTypedefs(uqtopusBoundaryCondition);

} // End namespace Foam

#endif

// ************************************************************************* //
